import { PrismaClient } from '@prisma/client'
import * as bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding SkillCart database with UPSC Telegram Services & 10 Marketplace Sections...')

  // Password hash for admin and sellers
  const passwordHash = await bcrypt.hash('AdminSecurePassword2026!', 10)
  const pinHash = await bcrypt.hash('1234', 10)

  // 1. Create Admin User if not exists
  const adminEmail = 'admin@skillcart.shop'
  let admin = await prisma.user.findUnique({ where: { email: adminEmail } })
  if (!admin) {
    admin = await prisma.user.create({
      data: {
        email: adminEmail,
        username: 'admin',
        passwordHash,
        transactionPinHash: pinHash,
        role: 'admin',
        referralCode: 'ADMIN2026',
        emailVerifiedAt: new Date(),
        profile: {
          create: {
            displayName: 'SkillCart Admin',
            bio: 'Official Marketplace Operations Manager',
            isVerified: true,
          },
        },
        wallet: {
          create: {
            availableBalance: 100000,
          },
        },
      },
    })
    console.log('Created Admin:', admin.username)
  }

  // 2. Create Third-Party Indian Sellers
  const sellersData = [
  {
    "name": "Ananya Sharma",
    "username": "ananya_upsc_2026",
    "email": "ananya.upsc@example.com"
  },
  {
    "name": "Rohit Kumar",
    "username": "delhi_aspirant_hub",
    "email": "rohit.aspirant@example.com"
  },
  {
    "name": "Chaitanya V",
    "username": "chaitanya_ias",
    "email": "chaitanya.v@example.com"
  },
  {
    "name": "Priya Nair",
    "username": "studyiq_notes_guru",
    "email": "priya.nair@example.com"
  },
  {
    "name": "Vikramaditya Singh",
    "username": "ias_baba_fan_99",
    "email": "vikram.baba@example.com"
  },
  {
    "name": "Siddharth Rao",
    "username": "orn_notes_seller",
    "email": "siddharth.rao@example.com"
  },
  {
    "name": "Meera Mukherjee",
    "username": "upsc_topper_notes",
    "email": "meera.topper@example.com"
  },
  {
    "name": "Aditya Verma",
    "username": "civil_services_prep",
    "email": "aditya.verma@example.com"
  },
  {
    "name": "Kavita Reddy",
    "username": "ias_mains_crack",
    "email": "kavita.reddy@example.com"
  },
  {
    "name": "Gaurav Joshi",
    "username": "csat_master_299",
    "email": "gaurav.csat@example.com"
  },
  {
    "name": "Neeraj Gupta",
    "username": "optional_hub_delhi",
    "email": "neeraj.gupta@example.com"
  },
  {
    "name": "Swati Deshmukh",
    "username": "upsc_drive_links",
    "email": "swati.deshmukh@example.com"
  }
];

  const createdSellers: any[] = []

  for (const s of sellersData) {
    let u = await prisma.user.findUnique({ where: { email: s.email } })
    if (!u) {
      u = await prisma.user.create({
        data: {
          email: s.email,
          username: s.username,
          passwordHash,
          transactionPinHash: pinHash,
          role: 'seller',
          referralCode: `REF_${s.username.toUpperCase()}`,
          emailVerifiedAt: new Date(),
          profile: {
            create: {
              displayName: s.name,
              bio: `Independent UPSC Content Creator & Telegram Educator (@${s.username})`,
              isVerified: true,
              location: 'Delhi, India',
            },
          },
          wallet: {
            create: {
              availableBalance: 5000,
            },
          },
        },
      })
    }
    createdSellers.push(u)
  }

  console.log(`Created/Verified ${createdSellers.length} Indian Sellers.`)

  // 3. Create 10 Top-Level Marketplace Sections
  const sectionCategories = [
    { name: 'Telegram Services', slug: 'telegram-services', description: 'UPSC courses, PDF test series, and notes sold by independent third-party sellers' },
    { name: 'Software & Scripts', slug: 'software-scripts', description: 'Web applications, Python bots, and developer automation tools' },
    { name: 'AI Prompts & Models', slug: 'ai-prompts-models', description: 'LLM prompt packs, Midjourney presets, and AI agent workflows' },
    { name: 'UI/UX Design Kits', slug: 'ui-ux-design-kits', description: 'Figma components, design systems, and icon sets' },
    { name: 'E-Books & Guides', slug: 'e-books-guides', description: 'Digital books, cheat sheets, and exam strategy guides' },
    { name: 'Video Tutorials & Courses', slug: 'video-tutorials-courses', description: 'Masterclasses, video lectures, and video workshops' },
    { name: 'Templates & Themes', slug: 'templates-themes', description: 'Notion dashboards, Next.js starters, and Webflow templates' },
    { name: 'Audio & Music Assets', slug: 'audio-music-assets', description: 'Podcast jingles, sound effects, and royalty-free tracks' },
    { name: 'Memberships & Subscriptions', slug: 'memberships-subscriptions', description: 'Exclusive community access and monthly digital downloads' },
    { name: 'Data & Analytics Datasets', slug: 'data-analytics-datasets', description: 'Cleaned datasets, CSV databases, and research reports' },
  ]

  const categoryMap = new Map<string, any>()

  for (const cat of sectionCategories) {
    let dbCat = await prisma.category.findUnique({ where: { slug: cat.slug } })
    if (!dbCat) {
      dbCat = await prisma.category.create({
        data: {
          name: cat.name,
          slug: cat.slug,
          description: cat.description,
        },
      })
    }
    categoryMap.set(cat.slug, dbCat)
  }

  // Create UPSC Subcategories under Telegram Services
  const telegramCat = categoryMap.get('telegram-services')

  const upscSubcategories = [
    'GS Foundation',
    'Integrated Prelims + Mains',
    'Prelims Crash Courses',
    'Mains Crash Courses',
    'Prelims Test Series',
    'Mains Test Series',
    'Answer Writing',
    'Current Affairs',
    'CSAT',
    'Essay',
    'Ethics',
    'Mentorship',
    'Interview Guidance',
    'Revision and Value Addition',
    'Optional - PSIR',
    'Optional - Public Administration',
    'Optional - Sociology',
    'Optional - Geography',
    'Optional - History',
    'Optional - Anthropology',
    'Optional - Philosophy',
    'Optional - Mathematics',
    'Optional - Commerce',
    'Optional - Economics',
    'Optional - Literature',
  ]

  for (const subName of upscSubcategories) {
    const slug = subName.toLowerCase().replace(/[^a-z0-9]+/g, '-')
    let sub = await prisma.category.findUnique({ where: { slug } })
    if (!sub) {
      await prisma.category.create({
        data: {
          name: subName,
          slug,
          parentId: telegramCat.id,
          description: `UPSC ${subName} Telegram course materials and PDFs`,
        },
      })
    }
  }

  // 4. Seed UPSC Listings into Telegram Services Section at ₹299
  const coursesRaw = [
  {
    "course_id": "UPSC-C-0001",
    "institute_name": "ALS IAS",
    "course_name": "General Studies Strategist Programme",
    "course_category": "Integrated Prelims + Mains Course",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "Not stated",
    "duration": "360 GS sessions; current batch length not stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute; official page does not publish current fee",
    "official_course_url": "https://www.alsias.net/best-upsc-coaching-institute-in-delhi",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Official ALS pages advertise classroom/online GS, tests, writing sessions and interview guidance.",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0002",
    "institute_name": "ALS IAS",
    "course_name": "Interview Guidance Programme",
    "course_category": "Interview Guidance Programme (Personality Test)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "Current cycle",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.alsias.net/best-upsc-coaching-institute-in-delhi",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0003",
    "institute_name": "ALS IAS",
    "course_name": "Anthropology Optional with Strategist Programme",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Anthropology",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "Not stated",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.alsias.net/best-upsc-coaching-institute-in-delhi",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Subject appears in the optionals list on official ALS centre pages.",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0004",
    "institute_name": "ALS IAS",
    "course_name": "Geography Optional with Strategist Programme",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Geography",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "Not stated",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.alsias.net/best-upsc-coaching-institute-in-delhi",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Subject appears in the optionals list on official ALS centre pages.",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0005",
    "institute_name": "ALS IAS",
    "course_name": "History Optional with Strategist Programme",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "History",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "Not stated",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.alsias.net/best-upsc-coaching-institute-in-delhi",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Subject appears in the optionals list on official ALS centre pages.",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0006",
    "institute_name": "ALS IAS",
    "course_name": "Kannada Literature Optional with Strategist Programme",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Kannada Literature",
    "mode": "Hybrid",
    "language": "Kannada/English",
    "target_exam_year": "Not stated",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.alsias.net/best-upsc-coaching-institute-in-delhi",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Subject appears in the optionals list on official ALS centre pages.",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0007",
    "institute_name": "ALS IAS",
    "course_name": "Political Science & International Relations Optional with Strategist Programme",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Political Science & International Relations",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "Not stated",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.alsias.net/best-upsc-coaching-institute-in-delhi",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Subject appears in the optionals list on official ALS centre pages.",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0008",
    "institute_name": "ALS IAS",
    "course_name": "Public Administration Optional with Strategist Programme",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Public Administration",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "Not stated",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.alsias.net/best-upsc-coaching-institute-in-delhi",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Subject appears in the optionals list on official ALS centre pages.",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0009",
    "institute_name": "ALS IAS",
    "course_name": "Sociology Optional with Strategist Programme",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Sociology",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "Not stated",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.alsias.net/best-upsc-coaching-institute-in-delhi",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Subject appears in the optionals list on official ALS centre pages.",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0010",
    "institute_name": "Chahal Academy",
    "course_name": "2 Year IAS/UPSC Course",
    "course_category": "GS Foundation Course",
    "optional_subject": "",
    "mode": "Offline",
    "language": "English/Bilingual",
    "target_exam_year": "2-year horizon",
    "duration": "2 years",
    "fee_min_inr": "159000",
    "fee_max_inr": "159000",
    "approximate_fee": "\u20b9159,000",
    "fee_notes": "",
    "official_course_url": "https://chahalacademy.com/ias-coaching",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0011",
    "institute_name": "Chahal Academy",
    "course_name": "3 Year IAS/UPSC Course",
    "course_category": "GS Foundation Course",
    "optional_subject": "",
    "mode": "Offline",
    "language": "English/Bilingual",
    "target_exam_year": "3-year horizon",
    "duration": "3 years",
    "fee_min_inr": "209000",
    "fee_max_inr": "209000",
    "approximate_fee": "\u20b9209,000",
    "fee_notes": "",
    "official_course_url": "https://chahalacademy.com/ias-coaching",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0012",
    "institute_name": "Chahal Academy",
    "course_name": "1 Year IAS/UPSC Course",
    "course_category": "Integrated Prelims + Mains Course",
    "optional_subject": "",
    "mode": "Offline",
    "language": "English/Bilingual",
    "target_exam_year": "Next exam cycle",
    "duration": "1 year",
    "fee_min_inr": "89000",
    "fee_max_inr": "89000",
    "approximate_fee": "\u20b989,000",
    "fee_notes": "",
    "official_course_url": "https://chahalacademy.com/ias-coaching",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0013",
    "institute_name": "Chahal Academy",
    "course_name": "UPSC Mock Interview",
    "course_category": "Interview Guidance Programme (Personality Test)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2025",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://chahalacademy.com/ias-mock-interview",
    "is_currently_active": "True",
    "active_status": "Active/on-demand page; target-year label on page is 2025",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0014",
    "institute_name": "Chahal Academy",
    "course_name": "Anthropology Optional Comprehensive Course",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Anthropology",
    "mode": "Hybrid",
    "language": "English/Bilingual",
    "target_exam_year": "Current cycle",
    "duration": "4\u20135 months; 1-year online access",
    "fee_min_inr": "25000",
    "fee_max_inr": "45000",
    "approximate_fee": "\u20b925,000\u2013\u20b945,000",
    "fee_notes": "Recorded \u20b925,000; live online \u20b940,000; offline \u20b945,000",
    "official_course_url": "https://chahalacademy.com/anthropology-optional",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Official subject page lists 120\u2013150 lectures, answer writing, class tests and mode-wise fees.",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0015",
    "institute_name": "Chahal Academy",
    "course_name": "Geography Optional Comprehensive Course",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Geography",
    "mode": "Hybrid",
    "language": "English/Bilingual",
    "target_exam_year": "Current cycle",
    "duration": "4\u20135 months; 1-year online access",
    "fee_min_inr": "25000",
    "fee_max_inr": "45000",
    "approximate_fee": "\u20b925,000\u2013\u20b945,000",
    "fee_notes": "Recorded \u20b925,000; live online \u20b940,000; offline \u20b945,000",
    "official_course_url": "https://chahalacademy.com/geography-optional",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Official subject page lists 120\u2013150 lectures, answer writing, class tests and mode-wise fees.",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0016",
    "institute_name": "Chahal Academy",
    "course_name": "History Optional Comprehensive Course",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "History",
    "mode": "Hybrid",
    "language": "English/Bilingual",
    "target_exam_year": "Current cycle",
    "duration": "4\u20135 months; 1-year online access",
    "fee_min_inr": "25000",
    "fee_max_inr": "45000",
    "approximate_fee": "\u20b925,000\u2013\u20b945,000",
    "fee_notes": "Recorded \u20b925,000; live online \u20b940,000; offline \u20b945,000",
    "official_course_url": "https://chahalacademy.com/history-optional",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Official subject page lists 120\u2013150 lectures, answer writing, class tests and mode-wise fees.",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0017",
    "institute_name": "Chahal Academy",
    "course_name": "Political Science & International Relations Optional Comprehensive Course",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Political Science & International Relations",
    "mode": "Hybrid",
    "language": "English/Bilingual",
    "target_exam_year": "Current cycle",
    "duration": "4\u20135 months; 1-year online access",
    "fee_min_inr": "25000",
    "fee_max_inr": "45000",
    "approximate_fee": "\u20b925,000\u2013\u20b945,000",
    "fee_notes": "Recorded \u20b925,000; live online \u20b940,000; offline \u20b945,000",
    "official_course_url": "https://chahalacademy.com/political-science",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Official subject page lists 120\u2013150 lectures, answer writing, class tests and mode-wise fees.",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0018",
    "institute_name": "Chahal Academy",
    "course_name": "Sociology Optional Comprehensive Course",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Sociology",
    "mode": "Hybrid",
    "language": "English/Bilingual",
    "target_exam_year": "Current cycle",
    "duration": "4\u20135 months; 1-year online access",
    "fee_min_inr": "25000",
    "fee_max_inr": "45000",
    "approximate_fee": "\u20b925,000\u2013\u20b945,000",
    "fee_notes": "Recorded \u20b925,000; live online \u20b940,000; offline \u20b945,000",
    "official_course_url": "https://chahalacademy.com/sociology-optional",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Official subject page lists 120\u2013150 lectures, answer writing, class tests and mode-wise fees.",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0019",
    "institute_name": "Chahal Academy",
    "course_name": "UPSC Prelims Special Crash Course",
    "course_category": "Prelims Crash Course",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2026",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://chahalacademy.com/upsc-prelims-special-crash-course",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "True",
    "is_test_series": "False",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0020",
    "institute_name": "Chanakya IAS Academy",
    "course_name": "Upgraded Foundation Course \u2014 1 Year",
    "course_category": "Integrated Prelims + Mains Course",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "English/Bilingual",
    "target_exam_year": "Current/next cycle",
    "duration": "1 year",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Current fees are centre-specific and provided on counselling",
    "official_course_url": "https://chanakyaiasacademy.com/courses/",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Official course page lists current 2026 centre batch notices and the 1/2/3-year UFC catalogue.",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0021",
    "institute_name": "Chanakya IAS Academy",
    "course_name": "Upgraded Foundation Course \u2014 2 Year",
    "course_category": "Integrated Prelims + Mains Course",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "English/Bilingual",
    "target_exam_year": "Current/next cycle",
    "duration": "2 years",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Current fees are centre-specific and provided on counselling",
    "official_course_url": "https://chanakyaiasacademy.com/courses/",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Official course page lists current 2026 centre batch notices and the 1/2/3-year UFC catalogue.",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0022",
    "institute_name": "Chanakya IAS Academy",
    "course_name": "Upgraded Foundation Course \u2014 3 Year",
    "course_category": "Integrated Prelims + Mains Course",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "English/Bilingual",
    "target_exam_year": "Current/next cycle",
    "duration": "3 years",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Current fees are centre-specific and provided on counselling",
    "official_course_url": "https://chanakyaiasacademy.com/courses/",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "Official course page lists current 2026 centre batch notices and the 1/2/3-year UFC catalogue.",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0023",
    "institute_name": "Chanakya IAS Academy",
    "course_name": "IAS Mock Interview",
    "course_category": "Interview Guidance Programme (Personality Test)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "English/Bilingual",
    "target_exam_year": "Current cycle",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact centre",
    "official_course_url": "https://chanakyaiasacademy.com/courses/",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0024",
    "institute_name": "Chanakya IAS Academy",
    "course_name": "Mains Guidance",
    "course_category": "Mains Crash Course",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "English/Bilingual",
    "target_exam_year": "Current cycle",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact centre",
    "official_course_url": "https://chanakyaiasacademy.com/courses/",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "True",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0025",
    "institute_name": "Chanakya IAS Academy",
    "course_name": "Optional Subject Coaching",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Multiple optionals \u2014 subjects not enumerated on current national course page",
    "mode": "Hybrid",
    "language": "English/Bilingual",
    "target_exam_year": "Current cycle",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Centre-specific; contact institute",
    "official_course_url": "https://chanakyaiasacademy.com/courses/",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0026",
    "institute_name": "Chanakya IAS Academy",
    "course_name": "Prelims Course",
    "course_category": "Prelims Crash Course",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "English/Bilingual",
    "target_exam_year": "Current cycle",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact centre; URL slug is legacy but linked by current official course catalogue",
    "official_course_url": "https://chanakyaiasacademy.com/upsc-prelims-2023/",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "True",
    "is_test_series": "False",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0027",
    "institute_name": "Chanakya IAS Academy",
    "course_name": "Prelims Test Series",
    "course_category": "Test Series (Prelims)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "English/Bilingual",
    "target_exam_year": "Current cycle",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact centre",
    "official_course_url": "https://chanakyaiasacademy.com/prelims-test-series/",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0028",
    "institute_name": "Drishti IAS",
    "course_name": "GS PYQ Answer Writing Course",
    "course_category": "Answer Writing Programme",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2026",
    "duration": "Until Mains 2026",
    "fee_min_inr": "10500",
    "fee_max_inr": "10500",
    "approximate_fee": "\u20b910,500",
    "fee_notes": "Mode/student-category dependent; see official fee table",
    "official_course_url": "https://www.drishtiias.com/mentorship/upsc/mains-mentorship-program-2026",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0029",
    "institute_name": "Drishti IAS",
    "course_name": "CSAT Batch",
    "course_category": "CSAT Course",
    "optional_subject": "",
    "mode": "Offline",
    "language": "English",
    "target_exam_year": "2027",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.drishtiias.com/classroom-program",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-08-03",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0030",
    "institute_name": "Drishti IAS",
    "course_name": "Applied Current Affairs Value-Added Course",
    "course_category": "Current Affairs Programme",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2026",
    "duration": "Until Mains 2026",
    "fee_min_inr": "7500",
    "fee_max_inr": "9500",
    "approximate_fee": "\u20b97,500\u2013\u20b99,500",
    "fee_notes": "Mode/student-category dependent; see official fee table",
    "official_course_url": "https://www.drishtiias.com/mentorship/upsc/mains-mentorship-program-2026",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0031",
    "institute_name": "Drishti IAS",
    "course_name": "Essay Batch",
    "course_category": "Essay Programme",
    "optional_subject": "",
    "mode": "Offline",
    "language": "English",
    "target_exam_year": "2026",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.drishtiias.com/classroom-program",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-08-10",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0032",
    "institute_name": "Drishti IAS",
    "course_name": "Essay Excellence Programme",
    "course_category": "Essay Programme",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2026",
    "duration": "Until Mains 2026",
    "fee_min_inr": "4500",
    "fee_max_inr": "6500",
    "approximate_fee": "\u20b94,500\u2013\u20b96,500",
    "fee_notes": "Mode/student-category dependent; see official fee table",
    "official_course_url": "https://www.drishtiias.com/mentorship/upsc/mains-mentorship-program-2026",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0033",
    "institute_name": "Drishti IAS",
    "course_name": "Ethics Enrichment Programme",
    "course_category": "Ethics (GS-IV) Course",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2026",
    "duration": "Until Mains 2026",
    "fee_min_inr": "6500",
    "fee_max_inr": "8500",
    "approximate_fee": "\u20b96,500\u2013\u20b98,500",
    "fee_notes": "Mode/student-category dependent; see official fee table",
    "official_course_url": "https://www.drishtiias.com/mentorship/upsc/mains-mentorship-program-2026",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0034",
    "institute_name": "Drishti IAS",
    "course_name": "GS Foundation Batch (English Medium)",
    "course_category": "Integrated Prelims + Mains Course",
    "optional_subject": "",
    "mode": "Offline",
    "language": "English",
    "target_exam_year": "2027",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official current batch page requires counselling for fee",
    "official_course_url": "https://www.drishtiias.com/classroom-program",
    "is_currently_active": "True",
    "active_status": "Active \u2014 upcoming August 2026 batches",
    "start_date": "2026-08-11 / 2026-08-26",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0035",
    "institute_name": "Drishti IAS",
    "course_name": "GS Foundation Batch (Hindi Medium)",
    "course_category": "Integrated Prelims + Mains Course",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Hindi",
    "target_exam_year": "2027",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.drishtiias.com/hindi/classroom-program",
    "is_currently_active": "True",
    "active_status": "Active \u2014 current classroom catalogue",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0036",
    "institute_name": "Drishti IAS",
    "course_name": "Interview Guidance Programme",
    "course_category": "Interview Guidance Programme (Personality Test)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2025/26 cycle",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.drishtiias.com/interview-guidance/",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0037",
    "institute_name": "Drishti IAS",
    "course_name": "Comprehensive Mains Mentorship 2026",
    "course_category": "Mentorship Programme",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2026",
    "duration": "Until Mains 2026",
    "fee_min_inr": "10000",
    "fee_max_inr": "20000",
    "approximate_fee": "\u20b910,000\u2013\u20b920,000",
    "fee_notes": "Mode/student-category dependent; see official fee table",
    "official_course_url": "https://www.drishtiias.com/mentorship/upsc/mains-mentorship-program-2026",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0038",
    "institute_name": "Drishti IAS",
    "course_name": "GS Mains Mentorship 2026",
    "course_category": "Mentorship Programme",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2026",
    "duration": "Until Mains 2026",
    "fee_min_inr": "8000",
    "fee_max_inr": "15000",
    "approximate_fee": "\u20b98,000\u2013\u20b915,000",
    "fee_notes": "Mode/student-category dependent; see official fee table",
    "official_course_url": "https://www.drishtiias.com/mentorship/upsc/mains-mentorship-program-2026",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0039",
    "institute_name": "Drishti IAS",
    "course_name": "UPSC Mentorship Programme (Foundation) 2027",
    "course_category": "Mentorship Programme",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2027",
    "duration": "Through Foundation, Integrated and Prelims phases",
    "fee_min_inr": "30000",
    "fee_max_inr": "70000",
    "approximate_fee": "\u20b930,000\u2013\u20b970,000",
    "fee_notes": "Online Hindi \u20b930,000; online English \u20b935,000; offline \u20b935,000\u2013\u20b970,000 depending on centre/library/student status",
    "official_course_url": "https://www.drishtiias.com/mentorship/upsc/ias-foundation-mentorship-programme-2027",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-06",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0040",
    "institute_name": "Drishti IAS",
    "course_name": "Optional PYQ Answer Writing Course",
    "course_category": "Optional Subject Answer Writing Programme",
    "optional_subject": "Multiple optionals",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2026",
    "duration": "Until Mains 2026",
    "fee_min_inr": "7999",
    "fee_max_inr": "7999",
    "approximate_fee": "\u20b97,999",
    "fee_notes": "Mode/student-category dependent; see official fee table",
    "official_course_url": "https://www.drishtiias.com/mentorship/upsc/mains-mentorship-program-2026",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0041",
    "institute_name": "Drishti IAS",
    "course_name": "Optional Subject Mentorship 2026",
    "course_category": "Optional Subject Answer Writing Programme",
    "optional_subject": "Multiple optionals",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2026",
    "duration": "Until Mains 2026",
    "fee_min_inr": "9500",
    "fee_max_inr": "10500",
    "approximate_fee": "\u20b99,500\u2013\u20b910,500",
    "fee_notes": "Mode/student-category dependent; see official fee table",
    "official_course_url": "https://www.drishtiias.com/mentorship/upsc/mains-mentorship-program-2026",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0042",
    "institute_name": "Drishti IAS",
    "course_name": "Anthropology Optional Classroom Programme",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Anthropology",
    "mode": "Offline",
    "language": "English",
    "target_exam_year": "2026\u201327",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.drishtiias.com/classroom-program/delhi-coaching-centre",
    "is_currently_active": "True",
    "active_status": "Active/in progress \u2014 listed on current Delhi centre page",
    "start_date": "2026-06-22",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0043",
    "institute_name": "Drishti IAS",
    "course_name": "Geography Optional Classroom Programme",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Geography",
    "mode": "Offline",
    "language": "English",
    "target_exam_year": "2026\u201327",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.drishtiias.com/classroom-program/delhi-coaching-centre",
    "is_currently_active": "True",
    "active_status": "Active/in progress \u2014 listed on current Delhi centre page",
    "start_date": "2026-06-11",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0044",
    "institute_name": "Drishti IAS",
    "course_name": "History Optional Classroom Programme",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "History",
    "mode": "Offline",
    "language": "English",
    "target_exam_year": "2026\u201327",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.drishtiias.com/classroom-program/delhi-coaching-centre",
    "is_currently_active": "True",
    "active_status": "Active/in progress \u2014 listed on current Delhi centre page",
    "start_date": "2026-07-10",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0045",
    "institute_name": "Drishti IAS",
    "course_name": "Political Science & International Relations Optional Classroom Programme",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Political Science & International Relations",
    "mode": "Offline",
    "language": "English",
    "target_exam_year": "2026\u201327",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.drishtiias.com/classroom-program/delhi-coaching-centre",
    "is_currently_active": "True",
    "active_status": "Active/in progress \u2014 listed on current Delhi centre page",
    "start_date": "2026-06-05",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0046",
    "institute_name": "Drishti IAS",
    "course_name": "Sociology Optional Classroom Programme",
    "course_category": "Optional Subject Foundation Course",
    "optional_subject": "Sociology",
    "mode": "Offline",
    "language": "English",
    "target_exam_year": "2026\u201327",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Contact institute",
    "official_course_url": "https://www.drishtiias.com/classroom-program/delhi-coaching-centre",
    "is_currently_active": "True",
    "active_status": "Active/in progress \u2014 listed on current Delhi centre page",
    "start_date": "2026-06-15",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0047",
    "institute_name": "Drishti IAS",
    "course_name": "Anthropology Optional Test Series 2026 \u2014 Package I",
    "course_category": "Optional Subject Test Series",
    "optional_subject": "Anthropology",
    "mode": "Hybrid",
    "language": "English",
    "target_exam_year": "2026",
    "duration": "16 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official page lists subject, test count and enrolment; public fee not shown",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-06-14",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0048",
    "institute_name": "Drishti IAS",
    "course_name": "Geography Optional Test Series 2026 \u2014 Package I",
    "course_category": "Optional Subject Test Series",
    "optional_subject": "Geography",
    "mode": "Hybrid",
    "language": "English",
    "target_exam_year": "2026",
    "duration": "16 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official page lists subject, test count and enrolment; public fee not shown",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-06-14",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0049",
    "institute_name": "Drishti IAS",
    "course_name": "Hindi Literature Optional Test Series 2026 \u2014 Package I",
    "course_category": "Optional Subject Test Series",
    "optional_subject": "Hindi Literature",
    "mode": "Hybrid",
    "language": "Hindi",
    "target_exam_year": "2026",
    "duration": "16 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official page lists subject, test count and enrolment; public fee not shown",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-06-14",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0050",
    "institute_name": "Drishti IAS",
    "course_name": "History Optional Test Series 2026 \u2014 Package I",
    "course_category": "Optional Subject Test Series",
    "optional_subject": "History",
    "mode": "Hybrid",
    "language": "English",
    "target_exam_year": "2026",
    "duration": "16 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official page lists subject, test count and enrolment; public fee not shown",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-06-14",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0051",
    "institute_name": "Drishti IAS",
    "course_name": "Philosophy Optional Test Series 2026 \u2014 Package I",
    "course_category": "Optional Subject Test Series",
    "optional_subject": "Philosophy",
    "mode": "Hybrid",
    "language": "English",
    "target_exam_year": "2026",
    "duration": "16 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official page lists subject, test count and enrolment; public fee not shown",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-06-14",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0052",
    "institute_name": "Drishti IAS",
    "course_name": "Political Science & International Relations Optional Test Series 2026 \u2014 Package I",
    "course_category": "Optional Subject Test Series",
    "optional_subject": "Political Science & International Relations",
    "mode": "Hybrid",
    "language": "English",
    "target_exam_year": "2026",
    "duration": "16 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official page lists subject, test count and enrolment; public fee not shown",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-06-14",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0053",
    "institute_name": "Drishti IAS",
    "course_name": "Psychology Optional Test Series 2026 \u2014 Package I",
    "course_category": "Optional Subject Test Series",
    "optional_subject": "Psychology",
    "mode": "Hybrid",
    "language": "English",
    "target_exam_year": "2026",
    "duration": "16 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official page lists subject, test count and enrolment; public fee not shown",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-06-14",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0054",
    "institute_name": "Drishti IAS",
    "course_name": "Public Administration Optional Test Series 2026 \u2014 Package I",
    "course_category": "Optional Subject Test Series",
    "optional_subject": "Public Administration",
    "mode": "Hybrid",
    "language": "English",
    "target_exam_year": "2026",
    "duration": "16 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official page lists subject, test count and enrolment; public fee not shown",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-06-14",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0055",
    "institute_name": "Drishti IAS",
    "course_name": "Sociology Optional Test Series 2026 \u2014 Package I",
    "course_category": "Optional Subject Test Series",
    "optional_subject": "Sociology",
    "mode": "Hybrid",
    "language": "English",
    "target_exam_year": "2026",
    "duration": "16 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official page lists subject, test count and enrolment; public fee not shown",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-06-14",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0056",
    "institute_name": "Drishti IAS",
    "course_name": "Sociology Optional Test Series 2026 \u2014 Package II",
    "course_category": "Optional Subject Test Series",
    "optional_subject": "Sociology",
    "mode": "Online",
    "language": "English",
    "target_exam_year": "2026",
    "duration": "8 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Public fee not shown",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-06-28",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0057",
    "institute_name": "Drishti IAS",
    "course_name": "IAS Mains Test Series 2027 \u2014 Package F",
    "course_category": "Test Series (Mains)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2027",
    "duration": "39 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Fee visible after enrolment/login; not published in public schedule",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-10-11",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0058",
    "institute_name": "Drishti IAS",
    "course_name": "IAS Mains Test Series 2027 \u2014 Package I",
    "course_category": "Test Series (Mains)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2027",
    "duration": "64 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Fee visible after enrolment/login; not published in public schedule",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-07-12",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0059",
    "institute_name": "Drishti IAS",
    "course_name": "IAS Mains Test Series 2027 \u2014 Package II",
    "course_category": "Test Series (Mains)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2027",
    "duration": "51 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Fee visible after enrolment/login; not published in public schedule",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-10-11",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0060",
    "institute_name": "Drishti IAS",
    "course_name": "IAS Mains Test Series 2027 \u2014 Package III",
    "course_category": "Test Series (Mains)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2027",
    "duration": "46 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Fee visible after enrolment/login; not published in public schedule",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-11-15",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0061",
    "institute_name": "Drishti IAS",
    "course_name": "IAS Mains Test Series 2027 \u2014 Package IV",
    "course_category": "Test Series (Mains)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2027",
    "duration": "36 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Fee visible after enrolment/login; not published in public schedule",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2027-01-23",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0062",
    "institute_name": "Drishti IAS",
    "course_name": "IAS Mains Test Series 2027 \u2014 Package V",
    "course_category": "Test Series (Mains)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2027",
    "duration": "24 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Fee visible after enrolment/login; not published in public schedule",
    "official_course_url": "https://www.drishtiias.com/upsc-mains-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2027-06-06",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0063",
    "institute_name": "Drishti IAS",
    "course_name": "Prelims Test Series 2027 Package F (44 GS + 33 CSAT)",
    "course_category": "Test Series (Prelims)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2027",
    "duration": "77 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official 2027 page publishes schedule but not fee in crawlable table",
    "official_course_url": "https://www.drishtiias.com/upsc-prelims-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-07-12",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0064",
    "institute_name": "Drishti IAS",
    "course_name": "Prelims Test Series 2027 Package I (24 GS + 16 CSAT)",
    "course_category": "Test Series (Prelims)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2027",
    "duration": "40 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official 2027 page publishes schedule but not fee in crawlable table",
    "official_course_url": "https://www.drishtiias.com/upsc-prelims-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-07-12",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0065",
    "institute_name": "Drishti IAS",
    "course_name": "Prelims Test Series 2027 Package II (44 GS)",
    "course_category": "Test Series (Prelims)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2027",
    "duration": "44 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official 2027 page publishes schedule but not fee in crawlable table",
    "official_course_url": "https://www.drishtiias.com/upsc-prelims-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-07-12",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0066",
    "institute_name": "Drishti IAS",
    "course_name": "Prelims Test Series 2027 Package III (33 CSAT)",
    "course_category": "Test Series (Prelims)",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "Bilingual",
    "target_exam_year": "2027",
    "duration": "33 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official 2027 page publishes schedule but not fee in crawlable table",
    "official_course_url": "https://www.drishtiias.com/upsc-prelims-test-series",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-08-01",
    "is_crash_course": "False",
    "is_test_series": "True",
    "has_answer_writing_component": "False",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0067",
    "institute_name": "Edukemy",
    "course_name": "UPSC Essay Mains Support Program 2026/27",
    "course_category": "Essay Programme",
    "optional_subject": "",
    "mode": "Online",
    "language": "English",
    "target_exam_year": "2026\u201327",
    "duration": "30+ hours; 24 videos + 8 live sessions; 3 months mentorship",
    "fee_min_inr": "6499",
    "fee_max_inr": "6499",
    "approximate_fee": "\u20b96,499",
    "fee_notes": "",
    "official_course_url": "https://edukemy.com/upsc/upsc-essay",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-06-11",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "False"
  },
  {
    "course_id": "UPSC-C-0068",
    "institute_name": "Edukemy",
    "course_name": "GS Foundation Course for UPSC CSE 2027",
    "course_category": "Integrated Prelims + Mains Course",
    "optional_subject": "",
    "mode": "Hybrid",
    "language": "English",
    "target_exam_year": "2027",
    "duration": "10+ months; 250+ live classes",
    "fee_min_inr": "90000",
    "fee_max_inr": "180000",
    "approximate_fee": "\u20b990,000\u2013\u20b9180,000",
    "fee_notes": "Online \u20b990,000; offline \u20b9174,500; hybrid \u20b9180,000",
    "official_course_url": "https://edukemy.com/upsc/gs-foundation-course",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "2026-07-20",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0069",
    "institute_name": "Edukemy",
    "course_name": "GS Advanced and Mentorship Program",
    "course_category": "Mains Crash Course",
    "optional_subject": "",
    "mode": "Online",
    "language": "English",
    "target_exam_year": "Current cycle",
    "duration": "5 months; 26 tests",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official page does not publicly display current fee",
    "official_course_url": "https://edukemy.com/upsc/gs-advanced",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "True",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  },
  {
    "course_id": "UPSC-C-0070",
    "institute_name": "Edukemy",
    "course_name": "GS Integrated Mentorship Program",
    "course_category": "Mentorship Programme",
    "optional_subject": "",
    "mode": "Online",
    "language": "English",
    "target_exam_year": "2027",
    "duration": "Not publicly stated",
    "fee_min_inr": "",
    "fee_max_inr": "",
    "approximate_fee": "Not publicly stated",
    "fee_notes": "Official current homepage advertises programme; public fee was not exposed in fetched page",
    "official_course_url": "https://edukemy.com/upsc/gs-integrated-mentorship-program",
    "is_currently_active": "True",
    "active_status": "Active \u2014 official page accepts enrolment/admission",
    "start_date": "",
    "is_crash_course": "False",
    "is_test_series": "False",
    "has_answer_writing_component": "True",
    "source_checked_date": "2026-07-31",
    "evidence_notes": "",
    "has_test_series_component": "True"
  }
];

  let createdCount = 0

  for (let i = 0; i < coursesRaw.length; i++) {
    const item = coursesRaw[i]
    const seller = createdSellers[i % createdSellers.length]

    const courseName = item.course_name || 'UPSC Complete Study Programme'
    const mode = item.mode || 'Online Telegram Channel'
    const targetYear = item.target_exam_year && item.target_exam_year !== 'Not stated' ? item.target_exam_year : '2026'
    
    // Exact Title Format: “[Course Name] — [Mode] — UPSC [Target Year] — Sold by [Seller Display Name]”
    const sellerName = sellersData[i % sellersData.length].name
    const title = `${courseName} — ${mode} — UPSC ${targetYear} — Sold by ${sellerName}`

    // Check if service already exists by title
    const existing = await prisma.service.findFirst({ where: { title } })
    if (!existing) {
      await prisma.service.create({
        data: {
          sellerId: seller.id,
          categoryId: telegramCat.id,
          title,
          slug: title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 80) + `-${i}`,
          description: `Independent third-party listing for ${courseName} (${item.institute_name || 'UPSC Prep'}). Includes lecture notes PDF, Telegram channel access, current affairs updates, and test series PDFs. Listed by independent seller ${sellerName}.`,
          price: 299, // Base Selling Price of exactly ₹299 (299 SC)
          deliveryDays: 1,
          revisionsAllowed: 1,
          status: 'active',
          featured: i % 4 === 0,
          views: 120 + (i * 17) % 500,
          ordersCount: 15 + (i * 7) % 80,
          rating: 4.8,
          reviewsCount: 12 + (i * 3) % 40,
          coverUrl: `https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&auto=format&fit=crop&q=80`,
          packages: {
            create: [
              {
                name: 'Basic Telegram Access',
                tier: 'basic',
                description: 'Instant Telegram channel link with lecture PDFs & test series',
                price: 299,
                deliveryDays: 1,
                features: '["Instant Telegram Channel Link", "PDF Notes & Slides", "Test Series PDFs", "Validity 1 Year"]',
              },
            ],
          },
        },
      })
      createdCount++
    }
  }

  console.log(`Seeded ${createdCount} UPSC Telegram Services listings at ₹299 fixed selling price!`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
